; z80bench export — Test Project
; Generated: Sun Mar 29 21:36:27 2026
; Assembler: z88dk/z80asm

        INCLUDE "symbols.sym"
        ORG     0x0000


; This is a very long block comment that should be wrapped at 77 characters of 
; content so that the total line length in the assembly output is 79 
; characters, but in the listing view it should be 100 characters because of 
; the 21 character listing zone prefix.
START:
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
                nop   
